// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyDatabase.h"
#include "EyamExpressoScripts.h"
#include "EyamDatabase.generated.h"

UCLASS(BlueprintType)
class PLAGUE_API UEyamDatabase : public UArticyDatabase
{
	GENERATED_BODY()
	
public:
	
	/** Get the instance (copy of the asset) of the database. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyDB", keywords="database"))
	static UEyamDatabase* Get(const UObject* WorldContext) 
	{
		return static_cast<UEyamDatabase*>(Super::Get(WorldContext));
	}
	
	/** Get the global variables. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UEyamGlobalVariables* GetGVs() const override
	{
		return static_cast<UEyamGlobalVariables*>(Super::GetGVs());
	}
	/** Gets the current runtime instance of a set of GVs. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UEyamGlobalVariables* GetRuntimeGVs(UArticyAlternativeGlobalVariables* Asset) const override
	{
		return static_cast<UEyamGlobalVariables*>(Super::GetRuntimeGVs(Asset));
	}
};
