// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyExpressoScripts.h"
#include "EyamGlobalVariables.h"
#include "EyamExpressoScripts.generated.h"

UINTERFACE(Blueprintable)
class UEyamMethodsProvider : public UInterface { GENERATED_BODY() };
class IEyamMethodsProvider
{
	GENERATED_BODY()
	
public:
};

UCLASS(BlueprintType, Blueprintable)
class PLAGUE_API UEyamExpressoScripts : public UArticyExpressoScripts
{
	GENERATED_BODY()
	
private:
	
	
private:
	
	mutable TWeakObjectPtr<UEyamGlobalVariables> ActiveGlobals = nullptr;
	
	void SetGV(UArticyGlobalVariables* GV) const override
	{
		auto gv = Cast<UEyamGlobalVariables>(GV);
		/** Initialize all GV namespace references (or nullify if we're setting to nullptr) */
		/** Store GVs */
		ActiveGlobals = gv;
	}
	
	UArticyGlobalVariables* GetGV() override
	{
		/** Return active global variables as set by SetGV */
		if(ActiveGlobals.IsValid()) { return ActiveGlobals.Get(); }
		return nullptr;
	}
	
	UClass* GetUserMethodsProviderInterface() override
	{
		return UEyamMethodsProvider::StaticClass();
	}
	
public:
	
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(push)
	#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
	#endif
	 UEyamExpressoScripts() 
	{
		Conditions.Add(-592068225, [&]
		{
			return ConditionOrTrue(
				//Find David's Satchel

			);
		});
		Conditions.Add(82082871, [&]
		{
			return ConditionOrTrue(
				//Did you pick any apples?

			);
		});
		Conditions.Add(-31745235, [&]
		{
			return ConditionOrTrue(
				//Did you eat any apples

			);
		});
		Conditions.Add(-1672428084, [&]
		{
			return ConditionOrTrue(
				//Is Godfrey's health above 50%

			);
		});
		Instructions.Add(42033406, [&]
		{
			//Receive GOD'S LOVE BUFF

		});
		Instructions.Add(268283309, [&]
		{
			//Receive x1 TAP APPLE

		});
		Instructions.Add(-1025294745, [&]
		{
			//Receive FRIEND OF THE DAEVIL BUFF

		});
		Instructions.Add(-1796211177, [&]
		{
			//As Godfrey gets close to Mrs Robertson

		});
	}
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(pop)
	#endif
};
